/** Accounts tracked by the dashboard. mergeKey groups wallets controlled by the same person/entity. */
export const WALLET_CONFIG = [
  { username: 'Gringotts_Wizarding_Bank', classification: 'FOUNDATION' },
  { username: 'FOCUS_COLD_000', classification: 'FOUNDATION' },
  { username: 'FOCUS_COLD_001', classification: 'FOUNDATION' },
  { username: 'focus', classification: 'FOUNDATION' },
  { username: 'openfund', classification: 'FOUNDATION' },
  { username: 'Deso', classification: 'FOUNDATION' },
  { username: 'AMM_DESO_24_PlAEU', classification: 'AMM' },
  { username: 'AMM_DESO_23_GrYpe', classification: 'AMM' },
  { username: 'AMM_focus_12_nzWku', classification: 'AMM' },
  { username: 'AMM_openfund_12_gOR1b', classification: 'AMM' },
  { username: 'AMM_DESO_19_W5vn0', classification: 'AMM' },
  { username: 'AMM_openfund_13_1gbih', classification: 'AMM' },
  { username: 'Whoami', classification: 'FOUNDER' },
  { username: 'Nader', classification: 'FOUNDER' },
  { username: 'Mossified', classification: 'FOUNDER' },
  { username: 'LazyNina', classification: 'FOUNDER' },
  { username: 'Jacobvan_', classification: 'FOUNDER' },
  { username: 'Ashdigital', classification: 'FOUNDER' },
  { username: 'Wintercounter', classification: 'FOUNDER' },
  { username: 'maebeam', classification: 'FOUNDER' },
  { username: 'redpartyhat', classification: 'FOUNDER' },
  { username: 'bluepartyhat', classification: 'FOUNDER' },
  { username: 'FastFreddie', classification: 'FOUNDER' },
  { username: 'JacksonDean', classification: 'FOUNDER' },
  { username: 'TyFischer', classification: 'FOUNDER' },
  { username: 'happy_penguin', classification: 'FOUNDER' },
  { username: 'Randhir', displayName: 'Randhir (Me)', classification: 'DESO_BULL' },
  { username: 'HighKey', classification: 'DESO_BULL', mergeKey: 'HighKey' },
  { username: 'JordanLintz', classification: 'DESO_BULL', mergeKey: 'HighKey' },
  { username: 'LukeLintz', classification: 'DESO_BULL', mergeKey: 'HighKey' },
  { username: 'HighKeyValidator', classification: 'DESO_BULL', mergeKey: 'HighKey' },
  { username: 'StarGeezer', classification: 'DESO_BULL', mergeKey: 'StarGeezer' },
  { username: 'SG_Vault', classification: 'DESO_BULL', mergeKey: 'StarGeezer' },
  { username: 'BeyondSocialValidator', classification: 'DESO_BULL', mergeKey: 'StarGeezer' },
  { username: 'StarGeezerCore', classification: 'DESO_BULL', mergeKey: 'StarGeezer' },
  { username: 'BeyondSocial', classification: 'DESO_BULL', mergeKey: 'StarGeezer' },
  { username: 'DesocialWorld', classification: 'DESO_BULL' },
  { username: 'Edokoevoet', classification: 'DESO_BULL' },
  { username: 'Gabrielist', classification: 'DESO_BULL', mergeKey: 'Gabrielist' },
  { username: 'gabrielvault', classification: 'DESO_BULL', mergeKey: 'Gabrielist' },
  { username: 'RobertGraham', classification: 'DESO_BULL' },
  { username: '0xAustin', classification: 'DESO_BULL' },
  { username: '0xBen_', classification: 'DESO_BULL' },
  { username: 'Darian_Parrish', classification: 'DESO_BULL', mergeKey: 'Darian_Parrish' },
  { username: 'DariansWallet', classification: 'DESO_BULL', mergeKey: 'Darian_Parrish' },
  { username: 'VishalGulia', classification: 'DESO_BULL' },
  { username: 'ZeroToOne', classification: 'DESO_BULL' },
  { username: 'anku', classification: 'DESO_BULL' },
  { username: 'fllwthrvr', classification: 'DESO_BULL' },
  { username: 'PremierNS', classification: 'DESO_BULL' },
  { username: 'WhaleDShark', classification: 'DESO_BULL' },
  { username: 'Fernando_Pessoa', classification: 'DESO_BULL' },
  { username: 'SkhiBridges', classification: 'DESO_BULL' },
  { username: 'Arnoud', classification: 'DESO_BULL' },
  { username: 'TangledBrush918', classification: 'DESO_BULL', mergeKey: 'TangledBrush918' },
  { username: 'Tangyshroom', classification: 'DESO_BULL', mergeKey: 'TangledBrush918' },
  { username: 'Moggel', classification: 'DESO_BULL', mergeKey: 'Moggel' },
  { username: 'BlastingBull67', classification: 'DESO_BULL', mergeKey: 'Moggel' },
  { username: 'SinisterSwine666', classification: 'DESO_BULL', mergeKey: 'Moggel' },
  { username: 'ReihanRei', classification: 'DESO_BULL', mergeKey: 'ReihanRei' },
  { username: 'AlecsandrosRei', classification: 'DESO_BULL', mergeKey: 'ReihanRei' },
  { username: 'mcMarsh', classification: 'DESO_BULL', mergeKey: 'mcMarsh' },
  { username: 'mcMarshstaking', classification: 'DESO_BULL', mergeKey: 'mcMarsh' },
  { username: 'jemarsh', classification: 'DESO_BULL', mergeKey: 'mcMarsh' },
  { username: 'dennishlewis', classification: 'DESO_BULL', mergeKey: 'dennishlewis' },
  { username: 'desonocode', classification: 'DESO_BULL', mergeKey: 'dennishlewis' },
  { username: 'SafetyNet', classification: 'DESO_BULL', mergeKey: 'SafetyNet' },
  { username: 'SafetyNetStaking', classification: 'DESO_BULL', mergeKey: 'SafetyNet' },
  { username: 'SafetyNetFunding', classification: 'DESO_BULL', mergeKey: 'SafetyNet' },
  { username: 'SafetyNetValidator', classification: 'DESO_BULL', mergeKey: 'SafetyNet' },
  { username: 'Silto_Nascao', classification: 'DESO_BULL' },
  { username: 'carry2web', classification: 'DESO_BULL' },
  { username: 'Kaanha', classification: 'DESO_BULL' },
  { username: 'Stevonagy', classification: 'DESO_BULL' },
  { username: 'mgoff', classification: 'DESO_BULL' },
  { username: 'Ugottalovit', classification: 'DESO_BULL' },
  { username: 'DesoWomenUnite', classification: 'DESO_BULL' },
  { username: 'Nordian', classification: 'DESO_BULL' },
  { username: 'DOZ', classification: 'DESO_BULL' },
  { username: 'markvanzee', classification: 'DESO_BULL' },
  { username: 'OliBvault', classification: 'DESO_BULL' },
  { username: 'Gjoe', classification: 'DESO_BULL' },
  { username: 'Briandrever', classification: 'DESO_BULL' },
  { username: 'Pradier', classification: 'DESO_BULL' },
  { username: 'StevoNagy', classification: 'DESO_BULL' },
  { username: 'erwinwillems', classification: 'DESO_BULL' },
  { username: 'Exotica_S', classification: 'DESO_BULL' },
  { username: 'JohnDWeb3', classification: 'DESO_BULL' },
  { username: 'gawergy', classification: 'DESO_BULL' },
  { username: 'nathanwells', classification: 'DESO_BULL' },
  { username: 'bkat', classification: 'DESO_BULL' },
  { username: 'jodybossert', classification: 'DESO_BULL' },
  { username: 'JohnJardin', classification: 'DESO_BULL', mergeKey: 'JohnJardin' },
  { username: 'Capatin', classification: 'DESO_BULL', mergeKey: 'JohnJardin' },
  { username: 'degen_doge', classification: 'DESO_BULL' },
  { username: 'kuririn', classification: 'DESO_BULL' },
  { username: 'fisnikee', classification: 'DESO_BULL' },
  { username: 'GoldBerry', classification: 'DESO_BULL', mergeKey: 'GoldBerry' },
  { username: 'GoldberryWal', classification: 'DESO_BULL', mergeKey: 'GoldBerry' },
  { username: 'ryleesnet', classification: 'DESO_BULL', mergeKey: 'ryleesnet' },
  { username: 'rylee19', classification: 'DESO_BULL', mergeKey: 'ryleesnet' },
  { username: 'ryleesnetvalidator', classification: 'DESO_BULL', mergeKey: 'ryleesnet' },
  { username: 'ChaseSteely', classification: 'DESO_BULL' },
  { username: 'CompDec', classification: 'DESO_BULL' },
  { username: 'RajLahoti', classification: 'DESO_BULL' },
  { username: 'StubbornDad', classification: 'DESO_BULL' },
  { username: 'TheBitcloutDog', classification: 'DESO_BULL' },
  { username: 'SharkGang', classification: 'DESO_BULL', mergeKey: 'SharkGang' },
  { username: 'Metaphilosopher', classification: 'DESO_BULL', mergeKey: 'SharkGang' },
  { username: 'SharkToken', classification: 'DESO_BULL', mergeKey: 'SharkGang' },
  { username: 'SharkBank', classification: 'DESO_BULL', mergeKey: 'SharkGang' },
  { username: 'SharkCoin', classification: 'DESO_BULL', mergeKey: 'SharkGang' },
  { username: 'Degen_doge', classification: 'DESO_BULL' },
  { username: 'PaulyHart', classification: 'DESO_BULL' },
  { username: 'Mher', classification: 'DESO_BULL' },
  { username: 'vampirecampfire', classification: 'DESO_BULL' },
];
